#server:
#  port: 6002
#spring:
#  application:
#    name: springbootConfig
#  profiles:
#    active: subversion
#  cloud:
#    config:
#      server:
#        svn:
#          uri: https://192.168.3.97/svn/SourceCode/SMPH/Beats/trunk/test/config
#          #username: *****
#          #password: *****
#          default-label:

server:
    port: 6002
spring:
  application:
    name: springbootConfig
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
            # 文件存放的绝对路径，源码里面我用绝对路径的方式放在了resources里面，这里需要改成自己的路径
#            search-locations: file:///Users/sunhan/Downloads/config  E:\config
            search-locations: E:/config
#             search-locations: classpath:/config
#是一个标志，指示服务器是否应从其自己的远程存储库配置自身，默认情况下，该标志处于关闭状态，因为它可能会延迟启动。但是，当嵌入到另一个应用程序中时，以与任何其他应用程序相同的方式初始化是有意义的
        bootstrap: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30