spring:
    application:
        name: springbootZuul

server:
    port: 6005

eureka:
    client:
        service-url:
            defaultZone : http://localhost:5000/eureka/

#zuul:
#    routes:
#        sbService :
#            path : /sbService/**
#            serviceId : springbootService
#            path : /sbService/**
#            serviceId : springbootService
#
#
zuul:
#  sensitiveHeaders: "abcd-test"
  routes:
    romp:
      path: /sbService/**
      serviceId: springbootService
#      sensitiveHeaders: "abcd-test"
#多个的时候，就直接配置多个，切记缩进
    basic_api:
      path: /basic_api/**
      serviceId: basicService

    test_api:
      path: /test_api/**
      serviceId: springbootService3
#     sensitiveHeaders: "abcd-test"